# Prefix
set-option -g prefix C-t

# Mouse enable
# set -g mouse off
set -g mouse on
# set-option -g mouse on
# unbind -T copy-mode-vi Enter
# bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
# bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# View
set -g status-interval 5
set -g status-left-length 16
set -g status-right-length 50

# Option
# set-window-option -g utf8 on
#set-window-option -g mode-keys vi
#set-window-option -g automatic-rename off
#set-option -g mouse-select-pane on
#set-option -g mouse-select-pane
#set-option -g mouse-resize-pane
set-option -g base-index 1

bind C-r source-file ~/.tmux.conf
bind C-n next-window
bind C-p previous-window
bind c new-window
#bind 1 break-pane
#bind 2 split-window -v
#bind 3 split-window -h
bind | split-window -h

bind C-k kill-pane
bind K kill-window
bind i display-panes
bind y copy-mode
#bind p paste-buffer

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Alt キーを押しながら矢印キーで、ペインサイズを変更する。
bind-key -nr M-Up resize-pane -U 5
bind-key -nr M-Down resize-pane -D 5
bind-key -nr M-Left resize-pane -L 5
bind-key -nr M-Right resize-pane -R 5

# macos or linux
if-shell 'test "$(uname -s)" = Darwin' "source-file ~/.tmux.conf.macos" "source-file ~/.tmux.conf.linux"

# unbind some keybind
unbind v

# powerline
# set-option -g default-terminal screen-256color
# set -g terminal-overrides 'xterm:colors=256'
# run-shell "powerline-daemon -q"
# run-shell "tmux set-environment -g POWERLINE_CONF $(pyenv prefix| xargs -I{} sh -c 'find {} -name powerline.conf')"
# if-shell 'test $POWERLINE_CONF != ""' 'source $POWERLINE_CONF'

# reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g base-index 1
set -g pane-base-index 1

set-option -g status-position bottom

set-option -g repeat-time 0

# Removes ESC delay
set -sg escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# Tokyo Night Dark theme
# bg=#1a1b26  fg=#c0caf5  active-tab=bg:#9ece6a,fg:#383e5a  inactive-tab=bg:#a9b1d6,fg:#383e5a
# active-border=#9ece6a  inactive-border=#383e5a

# Pane border colors
set -g pane-border-style "fg=#5a5a5a"
set -g pane-active-border-style "fg=#00ffc8"

# Status bar colors
set -g status-style "fg=#c0caf5,bg=#1a1b26"
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-style "fg=#1a1b26,bg=#a9b1d6"
set -g window-status-current-style "fg=#1a1b26,bg=#f7768e,bold"
set -g window-status-separator ''
set -g window-status-format "#[fg=#1a1b26,bg=#a9b1d6] #I:#W #[fg=#a9b1d6,bg=#1a1b26,nobold]"
set -g window-status-current-format "#[fg=#1a1b26,bg=#f7768e,bold] #I:#W #[fg=#f7768e,bg=#1a1b26,nobold]"
set -g status-left '#[fg=#c0caf5,bg=#3d59a1,bold] %Y-%m-%d(%a) %H:%M '
set -g status-right ''
