require('base')
require('autocmds')
require('plugins')
require('options')
require('keymaps')
require('colorscheme')
require('lsp')
require('completion')
require('statusline')
require('telescope_conf')
require('language')
require('startup_nvim')
require('neo-tree-config')

